name: Go

on:
    push:
        paths:
        - '.github/workflows/go.yml'
        - 'go/**'
        - '!go/README.md'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 8
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, macos-latest]
        go-version: [1.13]

    steps:
    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Get dependencies
      run: |
        cd go
        go get -v -t -d ./...
    - name: Build
      run: |
        cd go
        go build -v ./...
    - name: Test
      run: |
        cd go
        go test -v ./...
    - name: Run example
      run: |
        cd go
        go run main.go
